/*
    Boost Software License - Version 1.0 - August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

#include <CxxSpec/Specification.hpp>
#include <type_traits>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <gtest/gtest.h>







namespace CxxSpec
{
namespace
{

std::map<std::string, SpecificationFunction> registeredSpec;

void registerSpecification(const std::string& desc, SpecificationFunction func)
{
    registeredSpec.insert(std::make_pair(desc, func));
}

}
}







static_assert(__LINE__ == 62, "must be line 62");
SPECIFICATION("An empty specification") // line 63
{
}

static_assert(__LINE__ == 67, "must be line 67");
SPECIFICATION("another empty specification") // line 68
{
}

TEST(SpecificationExecutorTest, RegisterSpecification)
{
    ASSERT_EQ(&CxxSpec__Specification_at_line_63, CxxSpec::registeredSpec["An empty specification"]);
    ASSERT_EQ(&CxxSpec__Specification_at_line_68, CxxSpec::registeredSpec["another empty specification"]);
}

SPECIFICATION("one section")
{
    SECTION("one")
    {
    }
}

namespace
{

enum SpecOp
{
    BEGIN_SPECIFICATION,
    END_SPECIFICATION,
    BEGIN_SECTION,
    END_SECTION
};

class SpecificationVisitor : public ::CxxSpec::ISpecificationVisitor
{
public:
    std::vector<SpecOp> ops;
    std::vector<std::string> descs;

    virtual void beginSpecification()
    {
        ops.push_back(BEGIN_SPECIFICATION);
    }

    virtual void endSpecification()
    {
        ops.push_back(END_SPECIFICATION);
    }

    virtual bool beginSection(const std::string& desc)
    {
        ops.push_back(BEGIN_SECTION);
        descs.push_back(desc);
        return true;
    }

    virtual void endSection()
    {
        ops.push_back(END_SECTION);
    }
};

}

TEST(SpecificationExecutorTest, OneSection)
{
    SpecificationVisitor sv;
    CxxSpec::registeredSpec["one section"](sv);
    ASSERT_EQ(4u, sv.ops.size());
    ASSERT_EQ(BEGIN_SPECIFICATION, sv.ops[0]);
    ASSERT_EQ(BEGIN_SECTION, sv.ops[1]);
    ASSERT_EQ(END_SECTION, sv.ops[2]);
    ASSERT_EQ(END_SPECIFICATION, sv.ops[3]);
}

SPECIFICATION("nested sections")
{
    SECTION("outer")
    {
        SECTION("inner")
        {
        }
    }
}

TEST(SpecificationExecutorTest, NestedSections)
{
    SpecificationVisitor sv;
    CxxSpec::registeredSpec["nested sections"](sv);
    ASSERT_EQ(6u, sv.ops.size());
    ASSERT_EQ(BEGIN_SPECIFICATION, sv.ops[0]);
    ASSERT_EQ(BEGIN_SECTION, sv.ops[1]);
    ASSERT_EQ("outer", sv.descs[0]);
    ASSERT_EQ(BEGIN_SECTION, sv.ops[2]);
    ASSERT_EQ("inner", sv.descs[1]);
    ASSERT_EQ(END_SECTION, sv.ops[3]);
    ASSERT_EQ(END_SECTION, sv.ops[4]);
    ASSERT_EQ(END_SPECIFICATION, sv.ops[5]);
}

SPECIFICATION("section sequence")
{
    SECTION("1") { }
    SECTION("2") { }
    SECTION("3") { }
}

TEST(SpecificationExecutorTest, SectionSequence)
{
    SpecificationVisitor sv;
    CxxSpec::registeredSpec["section sequence"](sv);
    ASSERT_EQ(8u, sv.ops.size());
    ASSERT_EQ(BEGIN_SECTION, sv.ops[1]);
    ASSERT_EQ(BEGIN_SECTION, sv.ops[3]);
    ASSERT_EQ(BEGIN_SECTION, sv.ops[5]);
    ASSERT_EQ(END_SECTION, sv.ops[6]);
}

namespace
{

int checkExecuteParam;
void checkExecute(int param)
{
    checkExecuteParam = param;
}

}

SPECIFICATION("execution")
{
    auto x = 7;
    checkExecute(x);
}

TEST(SpecificationExecutorTest, SpecificationExecution)
{
    SpecificationVisitor sv;
    checkExecuteParam = 0;
    CxxSpec::registeredSpec["execution"](sv);
    ASSERT_EQ(7, checkExecuteParam);
}

namespace
{

int selectionIndex;

class SelectionVisitor : public CxxSpec::ISpecificationVisitor
{
public:

    SelectionVisitor(const std::set<std::string>& selection)
        : selection(selection) { }

    virtual void beginSpecification() { }
    virtual void endSpecification() { }

    virtual bool beginSection(const std::string& desc)
    {
        return selection.count(desc) > 0;
    }

    virtual void endSection() { }

private:
    std::set<std::string> selection;
};

}

SPECIFICATION("selection")
{
    SECTION("first")
    {
        selectionIndex = 1;
        SECTION("second")
        {
            selectionIndex = 2;
        }
    }
    SECTION("third")
    {
        selectionIndex = 3;
    }
}

void runSelection(std::set<std::string> selection)
{
    selectionIndex = 0;
    SelectionVisitor sv(selection);
    CxxSpec::registeredSpec["selection"](sv);
}

TEST(SpecificationExecutorTest, SectionSelectionFirst)
{
    std::set<std::string> selection;
    selection.insert("first");
    runSelection(selection);
    ASSERT_EQ(1, selectionIndex);
}

TEST(SpecificationExecutorTest, SectionSelectionSecond)
{
    std::set<std::string> selection;
    selection.insert("first");
    selection.insert("second");
    runSelection(selection);
    ASSERT_EQ(2, selectionIndex);
}

TEST(SpecificationExecutorTest, SectionSelectionThird)
{
    std::set<std::string> selection;
    selection.insert("third");
    runSelection(selection);
    ASSERT_EQ(3, selectionIndex);
}

TEST(SpecificationExecutorTest, SectionSelectionNone)
{
    std::set<std::string> selection;
    selection.insert("second");
    runSelection(selection);
    ASSERT_EQ(0, selectionIndex);
}
