/*
    Boost Software License - Version 1.0 - August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/


#ifndef CXXSPEC_SPECIFICATION_HPP
#define CXXSPEC_SPECIFICATION_HPP

#define CXXSPEC_CAT2(a, b) a##b
#define CXXSPEC_CAT(a, b) CXXSPEC_CAT2(a, b)
#define SPECIFICATION(desc) \
    void CXXSPEC_CAT(CxxSpec__Specification_at_line_, __LINE__)(::CxxSpec::ISpecificationVisitor&); \
    static int CXXSPEC_CAT(CxxSpec__Specification_register_at_line_, __LINE__) \
        = (::CxxSpec::registerSpecification(desc, &CXXSPEC_CAT(CxxSpec__Specification_at_line_, __LINE__)), 0); \
    void CXXSPEC_CAT(CxxSpec__Specification_at_line_, __LINE__)(::CxxSpec::ISpecificationVisitor& CxxSpec_specificationVisitor)

#define SECTION(desc) \
    if (const auto& CxxSpec_sectionGuard = ::CxxSpec::SectionGuard(CxxSpec_specificationVisitor))

namespace CxxSpec {

class ISpecificationVisitor
{
public:
    virtual ~ISpecificationVisitor() { }
    virtual void beginSection() = 0;
    virtual void endSection() = 0;
};

class SectionGuard
{
public:
    explicit SectionGuard(ISpecificationVisitor& sv) : sv(sv)
    {
        sv.beginSection();
    }

    ~SectionGuard()
    {
        sv.endSection();
    }

    operator bool() const { return true; }

private:
    ISpecificationVisitor& sv;
};

typedef void (*SpecFunction)(ISpecificationVisitor&);

}

#endif // CXXSPEC_SPECIFICATION_HPP
