/*
    Boost Software License - Version 1.0 - August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/


#ifndef CXXSPEC_SPECIFICATIONEXECUTOR_HPP
#define CXXSPEC_SPECIFICATIONEXECUTOR_HPP
#include <CxxSpec/ISpecificationVisitor.hpp>
#include <deque>
#include <vector>

namespace CxxSpec {

class SpecificationExecutor : public ISpecificationVisitor
{
public:
    SpecificationExecutor() { }

    virtual void beginSpecification()
    {
        state.beginSection = &SpecificationExecutor::following_beginSection;
        state.endSection = &SpecificationExecutor::following_endSection;

        path.swap(nextPath);
        moreNodes = false;
        nodeCount.resize(1);
    }

    virtual void endSpecification()
    {
    }

    virtual bool beginSection(const std::string& desc)
    {
        return (this->*state.beginSection)(desc);
    }

    virtual void endSection()
    {
        (this->*state.endSection)();
    }

    bool done() const
    {
        return !moreNodes;
    }

private:

    std::deque<bool> path, nextPath;
    std::vector<int> nodeCount;
    bool moreNodes;

    struct State
    {
        bool (SpecificationExecutor:: *beginSection)(const std::string& desc);
        void (SpecificationExecutor:: *endSection)();
    };

    State state;

    void pushCount()
    {
        nodeCount.back()++;
        nodeCount.push_back(0);
    }

    void popCount()
    {
        int n = nodeCount.back();
        if (n == 0) n = 1;
        while (n--)
            nextPath.pop_back();
        nodeCount.pop_back();
    }

    bool getNextStep()
    {
        if (path.empty())
        {
            state.beginSection = &SpecificationExecutor::running_beginSection;
            state.endSection = &SpecificationExecutor::running_endSection;
            return true;
        }
        bool next = path.front();
        path.pop_front();
        return next;
    }

    bool following_beginSection(const std::string& desc)
    {
        nodeCount.back()++;
        nodeCount.push_back(0);

        bool enter = getNextStep();
        nextPath.push_back(enter);
        return enter;
    }

    void following_endSection()
    {
        nodeCount.pop_back();
    }

    bool running_beginSection(const std::string& desc)
    {
        pushCount();
        nextPath.push_back(true);
        return true;
    }

    void running_endSection()
    {
        state.beginSection = &SpecificationExecutor::expectNode_beginSection;
        state.endSection = &SpecificationExecutor::expectNode_endSection;

        popCount();
    }

    bool expectNode_beginSection(const std::string& desc)
    {
        pushCount();

        moreNodes = true;

        nextPath.push_back(false);
        state.beginSection = &SpecificationExecutor::finishing_beginSection;
        state.endSection = &SpecificationExecutor::finishing_endSection;
        return false;
    }

    void expectNode_endSection()
    {
        popCount();
    }

    bool finishing_beginSection(const std::string&)
    {
        return false;
    }

    void finishing_endSection()
    {
    }
};

}

#endif // CXXSPEC_SPECIFICATIONEXECUTOR_HPP
